; TEST_RETURN_CODE=PASS
; TEST_COMMENT= Test symbol? predicat

(symbol? ())
(symbol? #t)
(symbol? #f)
(symbol? 5)
(symbol? -17)
(symbol? +28)
(symbol? #\o)
(symbol? #\8)
(symbol? #\space)
(symbol? #\newline)
(symbol? "")
(symbol? "vrai")
(symbol? (1))
(symbol? (1 2))
(symbol? 'j)
(symbol? '5)
(symbol? '#t)
(symbol? '"oui")
(define x 2)
(symbol? x)
(define y 'h)
(symbol? y)
