==> "this is a string"
==> " "
==> "another string with some scheme char inside #\t "
==> "a string with some parenthesis inside ( plop"
==> "a string with some parenthesis inside )"
==> "a string with some parenthesis inside # )"
==> "a string with some parenthesis inside # ("
==> "a string with some parenthesis inside ) ( plop"
==> "a string with some parenthesis inside ( ) (()))"
==> "semi colon inside a string is not a comment ; ; ;  "
